# Generated by Django 3.2.4 on 2021-07-14 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_todo_todo_task'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='id',
        ),
        migrations.AddField(
            model_name='code',
            name='todo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='todoapp.todo'),
        ),
        migrations.AlterField(
            model_name='code',
            name='room_code',
            field=models.CharField(max_length=10),
        ),
    ]
